language: csharp
deploy:
  provider: script
  skip_cleanup: true
  script: nuget pack -NoDefaultExcludes && nuget update -self && nuget push *.nupkg $api_key -Source https://www.nuget.org/api/v2/package
  on:
    branch: master